apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/mkotelni/backend:0.0.4
          ports:
            - containerPort: 5000
              name: backend
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
